version: '3.4'

services:

  postgres:
    image: postgres:16
    container_name: volttron-postgres
    environment:
      POSTGRES_DB: volttron
      POSTGRES_USER: volttron
      POSTGRES_PASSWORD: ec0l0ng
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5433"

  volttron1:
    container_name: volttron1
    hostname: volttron1
    build:
      context: .
      dockerfile: Dockerfile
    image: eclipsevolttron/volttron:test-build
    ports:
      # host_port:container_port
      # http port for volttron central
      - 8443:8443
    volumes:
      - ./platform_config.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
      - volttron1-volume:/home/volttron/db
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
      - TZ=America/Los_Angeles
    depends_on:
      - postgres

volumes:
  volttron1-volume:
    name: volttron1-data
  postgres-data:
